## Numpy 

It is a library (veryfamous library) which is used to process or work with arrays.
    Numpy full form Numerical Python. Any thing that can be converted in to an array is processed by numpy.

In [2]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
np.array([10,11,13])

array([10, 11, 13])

In [6]:
np.array([[1,2],[8,9]])

array([[1, 2],
       [8, 9]])

In [7]:
np.array([[['a','b'],['c','d'],['e','f']]])

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']]], dtype='<U1')

In [8]:
# Create a 2d Array
arry_2 = np.array([range(1,5),range(2,6),range(3,7)])

In [9]:
arry_2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [10]:
np.ndim(arry_2)

2

In [11]:
np.shape(arry_2)

(3, 4)

In [12]:
np.size(arry_2)

12

In [13]:
arry_2.dtype

dtype('int64')

In [14]:
np.zeros(5) # one d array with all 0

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3)) # Creates 2*3 array of all zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(9) #creates one d array with 9items with all ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [21]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
np.linspace(1,10,1000)

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

# Reshaping Arrays

In [23]:
arry_2 = np.array([range(10,16),range(11,17),range(12,18),range(13,19),range(14,20),range(15,21)])

In [24]:
arry_2

array([[10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20]])

In [25]:
np.shape(arry_2)

(6, 6)

In [27]:
np.size(arry_2)

36

In [30]:
arry_2.reshape(4,9)

array([[10, 11, 12, 13, 14, 15, 11, 12, 13],
       [14, 15, 16, 12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18, 14, 15, 16],
       [17, 18, 19, 15, 16, 17, 18, 19, 20]])

## Indexing and slicing of Array in Numpy

In [31]:
# sLicing 1 D array
str_a = np.array(list("sagarmatha"))

In [32]:
len_a = len(str_a)
len_a

10

In [33]:
str_a[0] # leftmost character

np.str_('s')

In [34]:
str_a[-1]

np.str_('a')

In [35]:
# first three characters from left to right
str_a[0:3]

array(['s', 'a', 'g'], dtype='<U1')

In [36]:
# first three characters from right to left
str_a[-1:-4:-1]

array(['a', 'h', 't'], dtype='<U1')

In [37]:
# slicing in 2D Array
l=['a','e','i','o','u']
x=['m','n','o','p','q']
j=['d','x','b','c','p']
p=['k','l','e','y','t']

In [38]:
st=np.array([l,x,j,p])
st

array([['a', 'e', 'i', 'o', 'u'],
       ['m', 'n', 'o', 'p', 'q'],
       ['d', 'x', 'b', 'c', 'p'],
       ['k', 'l', 'e', 'y', 't']], dtype='<U1')

In [39]:
np.size(st)

20

In [40]:
np.shape(st)

(4, 5)

In [43]:
st

array([['a', 'e', 'i', 'o', 'u'],
       ['m', 'n', 'o', 'p', 'q'],
       ['d', 'x', 'b', 'c', 'p'],
       ['k', 'l', 'e', 'y', 't']], dtype='<U1')

In [45]:
st[0:2,0:2]

array([['a', 'e'],
       ['m', 'n']], dtype='<U1')

In [46]:
st[0:4,0:2]

array([['a', 'e'],
       ['m', 'n'],
       ['d', 'x'],
       ['k', 'l']], dtype='<U1')

In [47]:
st[:,0]

array(['a', 'm', 'd', 'k'], dtype='<U1')

In [48]:
st[:,3]

array(['o', 'p', 'c', 'y'], dtype='<U1')

In [49]:
st[0,:]

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [50]:
st[3,:]

array(['k', 'l', 'e', 'y', 't'], dtype='<U1')

In [51]:
# Boolean Indexing
True or False
arry_2

array([[10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20]])

In [52]:
# fetch all numbers divisble by 2
arry_2[arry_2 % 2 == 0]

array([10, 12, 14, 12, 14, 16, 12, 14, 16, 14, 16, 18, 14, 16, 18, 16, 18,
       20])

In [53]:
arry_2 % 2 # REmainder

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]])

In [54]:
arry_2 % 2 == 0

array([[ True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True]])

In [55]:
arry_2[arry_2 % 2 == 0]

array([10, 12, 14, 12, 14, 16, 12, 14, 16, 14, 16, 18, 14, 16, 18, 16, 18,
       20])

In [56]:
arry_2

array([[10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20]])

In [58]:
# select all values not div by 2 and  3
arry_2[(arry_2 %2 !=0) & (arry_2 %3 !=0)]

array([11, 13, 11, 13, 13, 17, 13, 17, 17, 19, 17, 19])

# Mathematical operations in Numpy

In [60]:
x= np.array([[9,10,11,14],[91,21,10,16]])
x

array([[ 9, 10, 11, 14],
       [91, 21, 10, 16]])

In [61]:
x + 3

array([[12, 13, 14, 17],
       [94, 24, 13, 19]])

In [62]:
x*3

array([[ 27,  30,  33,  42],
       [273,  63,  30,  48]])

In [63]:
x / 7

array([[ 1.28571429,  1.42857143,  1.57142857,  2.        ],
       [13.        ,  3.        ,  1.42857143,  2.28571429]])

In [64]:
x.sum(axis=1) # denotes to work on row

array([ 44, 138])

In [65]:
x.sum(axis=0) #find sum columns

array([100,  31,  21,  30])

In [67]:
x.sum() #adds all items

np.int64(182)

In [68]:
arry_2

array([[10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20]])

In [69]:
arry_2.std()

np.float64(2.41522945769824)

In [70]:
arry_2.std()

np.float64(2.41522945769824)

In [71]:
arry_2.std(axis=0)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513,
       1.70782513])

In [72]:
x

array([[ 9, 10, 11, 14],
       [91, 21, 10, 16]])

In [74]:
y=x*3

In [75]:
y

array([[ 27,  30,  33,  42],
       [273,  63,  30,  48]])

In [76]:
x+y

array([[ 36,  40,  44,  56],
       [364,  84,  40,  64]])

In [77]:
x*y

array([[  243,   300,   363,   588],
       [24843,  1323,   300,   768]])

In [78]:
x/y

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [79]:
z = np.array([[10,11],[12,16]])
z

array([[10, 11],
       [12, 16]])

In [80]:
x

array([[ 9, 10, 11, 14],
       [91, 21, 10, 16]])

In [82]:
# t
t=np.arange(1,5)
t

array([1, 2, 3, 4])

In [83]:
x+t

array([[10, 12, 14, 18],
       [92, 23, 13, 20]])

In [84]:
x*t 

array([[ 9, 20, 33, 56],
       [91, 42, 30, 64]])

In [85]:
x/t

array([[ 9.        ,  5.        ,  3.66666667,  3.5       ],
       [91.        , 10.5       ,  3.33333333,  4.        ]])

In [89]:
arry_2

array([[10, 11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15, 16],
       [12, 13, 14, 15, 16, 17],
       [13, 14, 15, 16, 17, 18],
       [14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20]])

In [90]:
x =arry_2+3

In [91]:
x.mean()

np.float64(18.0)

In [93]:
x.mean(axis=0)

array([15.5, 16.5, 17.5, 18.5, 19.5, 20.5])

In [94]:
x.mean(axis=1)

array([15.5, 16.5, 17.5, 18.5, 19.5, 20.5])